#!/bin/sh
set -eu

"$GZ" -cd linux*.tar.gz | tar -x
cd linux*/

flags="ARCH=$ARCH CROSS_COMPILE=$ARCH-linux-musl- LEX=$LEX YACC=$YACC"

"$MAKE" $flags headers

for f in $(cd usr && find include -name '*.h' -type f)
do
	mkdir -p "$PREFIX/${f%/*}"
	cp -f "usr/$f" "$PREFIX/$f"
done

"$MAKE" $flags defconfig
./scripts/config --disable MODULES

"$MAKE" $flags

mkdir -p "$PREFIX/boot"
cp -Lf $(find arch -name 'zImage' \
                -o -name 'bzImage' \
                -o -name 'Image.gz' \
                -o -name 'uImage' \
                -o -name 'vmlinux.bin' | head -n 1) "$PREFIX/boot/linux"
